### ISSUE TITLE
Why is `sdlog = exp(sdlog)`?

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#100]
This line seems strange:

https://github.com/epinowcast/epidist/blob/f308cd0cdae3b0c35113eb23f1c08654d665c035/R/fitting-and-postprocessing.R#L173

Any idea what's happening there @seabbs @parksw3?

Also in `add_natural_scale_mean_sd` we have:

https://github.com/epinowcast/epidist/blob/f308cd0cdae3b0c35113eb23f1c08654d665c035/R/fitting-and-postprocessing.R#L132-L140

What about reusing `mean` on L137?

**Comment by seabbs** [comment]
> This line seems strange:

Check out the stan code. Its because it is modelled with a log link.

**Comment by athowes** [comment]
Propose changing the `setnames` here to be more informative e.g. `sdlog_log`

https://github.com/epinowcast/epidist/blob/f308cd0cdae3b0c35113eb23f1c08654d665c035/R/fitting-and-postprocessing.R#L168-L171

Is it worth making change to `add_natural_scale_mean_sd` to reuse `mean` in definition of `sd`?

**Comment by seabbs** [comment]
yup agree
