### ISSUE TITLE
Unit testing for `latent_individual` model and components

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#106]
## Goal 

Add unit testing for the `latent_individual` model and its components.

## Context

The package was recently refactored to use S3 methods for the first model we agreed to support. This is the code I am most familiar with, is important functionality, and am most sure will remain relevant in the package. As such, I think this is the right place to start with adding unit tests to the package. I had been doing this informally before (#84). 

A PR for this issue would close #23, #84.

## Required features

- Unit tests for:
  - `epidist_prepare` with `model = "latent_individual"`
  - `epidist_formula.epidist_latent_individual`
  - `epidist_prior.epidist_latent_individual` (after merge of PR https://github.com/epinowcast/epidist/pull/95)
  - `epidist_stancode.epidist_latent_individual`
  - `epidist.epidist_latent_individual`
- Slight stretch but I think worthwhile to do here are unit tests for the default versions of these methods
  - I don't think this would be hard to do

## Related documents

- #70

**Comment by athowes** [comment]
Point of uncertainty here whether unit tests written here should be passing, or should be intended to be passed in future.

I favour "intended to be passed in future". (Such that I don't think a PR closing this issue needs to pass tests.)

**Comment by seabbs** [comment]
I don't think we should be having unit tests that fail on `main` now. 

If we want to shift towards test driven design (having unit tests that currently fail but that we aim to make pass). I think we should do that as part of PRs (i.e commit 1 make some unit tests for a new feature - rest of PR is writing code to get these passing).

**Comment by athowes** [comment]
Ok, happy to do that.

Would it work for me to comment out proposed unit tests which currently fail? Would be slightly easier for me then to uncomment and open PRs to pass them.
