### ISSUE TITLE
Document remaining functions

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#11]
Many functions in the package do not appear to have `roxygen2` documentation (most in [R/fitting-and-postprocessing.R](https://github.com/epinowcast/epidist/blob/main/R/fitting-and-postprocessing.R), [R/models.R](https://github.com/epinowcast/epidist/blob/main/R/models.R), [R/observe.R](https://github.com/epinowcast/epidist/blob/main/R/observe.R), [R/plot-helpers.R](https://github.com/epinowcast/epidist/blob/main/R/plot-helpers.R), [R/plot.R](https://github.com/epinowcast/epidist/blob/main/R/plot.R), ...). I suggest documenting these functions.

**Comment by seabbs** [comment]
I think this issue could do with being split into several for the appropriate parts of the code base. I also think its currently blocked by needing a clear plan to move from the research code base towards a more flexible user facing package (as we will shed some code - particularly models).

**Comment by athowes** [comment]
I am closing this issue as it is not helpful. All functions are documented sufficient to pass tests. Better documentation for particular functions can be handled with new issues as Sam suggests, after we are more sure that they are worth having in the package.
