### ISSUE TITLE
Add package website

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#12]
The package does not have a rendered Github pages website. I suggest adding one, and that it follow the same conventions as other Epinowcast community packages which are not `epinowcast` itself, e.g. that of `hashprng`.

**Comment by seabbs** [comment]
yes agree - not that this should probably include using the `epinowcast` theme and making use of `roxygen2` keywords to organise the reference section.

**Comment by athowes** [comment]
"not that this should" is a typo and it should be "note that this should"?

Agree that there should be `roxygen2` keywords so that the Reference section in organised. Open to opinions about grouping functions together. Might have a go at this, and will just do what seems natural / group based on file.

**Comment by athowes** [comment]
I've started working on this on a branch on my fork at `athowes/epidist/add-website`.

I see that other `epinowcast` websites are deployed via a `gh-pages` branch from the main repository. I am unsure how to set this up as a PR from my fork, so will wait for guidance before proceeding with this.

I can do the `roxygen2` keywords as described above though (I have the website rendering fine with the same theme as `epinowcast` locally).

**Comment by seabbs** [comment]
So essentially from a fork you can do everything apart from create the branch we need so I would go ahead and do that. Hopefully when #18 is merged we can move to the next contribution step and give you repo access to make this all easier.

**Comment by athowes** [comment]
I think we can close this once we have the website rendering fine at http://epidist.epinowcast.org/. For some reason it's not doing that ATM. Any ideas why?

**Comment by seabbs** [comment]
I need to go and set up the subdomain to point at it. Will do today

**Comment by athowes** [comment]
Package site is up! Check http://epidist.epinowcast.org/
