### ISSUE TITLE
Make sure all CI is running and is feature complete

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#13]
As a first step before any development we need to make sure that all required CI is in place and that it works as expected.

**Comment by seabbs** [comment]
Fair enough. 

We likely want github actions to: 

- Build the `pkgdown`
- Do a Rmd check against multiple OS's (if we have things in our tests we don't expect to run on CRAN then we might also way two versions of this (i.e with and without those tests being skipped)
- Lint the package using `lintr`.
- Manage the deployment of our README and the use of the all contributors bot.
- Check our cmdstan code works with the latest version of Cmdstanr (optional/stretch goal). 
- Benchmarking using `touchstone` (also a stretch goal/its own issue).
- 
All of these are implemented for `epinowcast` and so in the first instance we can mostly just copy them across and read through them to check there is nothing specific to `epinowcast` in them.

That donee we can change our branch protection rules for `main` to start requiring some of them be be successful prior to merging

**Comment by athowes** [comment]
I suggest we do #60 and then after that I have a go at working through these remaining ones (to the extent they're not already working):

* [ ] Build the pkgdown
* [ ] Do a Rmd check against multiple OS's (if we have things in our tests we don't expect to run on CRAN then we might also use two versions of this [i.e with and without those tests being skipped])
* [ ] Lint the package using lintr
* [ ] Code coverage with codecov
* [ ] Manage the deployment of our README and the use of the all contributors bot #60
* [ ] Check our cmdstan code works with the latest version of Cmdstanr (optional)
* [ ] Benchmarking using touchstone (optional)
