### ISSUE TITLE
Updates to README

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#132]
I think that our `README.Rmd` file could be rewritten to provide a better introduction to the package. I think that this can wait until our "initial release" version is complete, but am writting an issue here now to log some ideas that I have.

* [x] #380
* [ ] Use > [!CAUTION] and other call out boxes e.g. for warning about the extent to which the package might change
* [ ] Put the Park et al. and Charniga et al. papers more front and center for users to refer to. I can see we have a link to the model vignette which doesn't exist yet: this should be made to link up
* [ ] Immediately direct users to the vignettes for the package, beginning with the "Get started"
* [ ] Posssibly: some kind of figure, perhaps explaining in a schematic what the package does. I think this could make things a lot more visually appealing

I'd be open to more suggestions / preferences about features to include in the README and what the focus should be on.

**Comment by seabbs** [comment]
> Posssibly: some kind of figure, perhaps explaining in a schematic what the package does. I think this could make things a lot more visually appealing

Great idea
