### ISSUE TITLE
Drop need for rstan in tests using posterior

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#134]
rstan is currently required for testing convergence but we can remove this dependency if we instead use the functionality from the `posteriors` package.

**Comment by athowes** [comment]
Agree on this but unsure `posterior` provides functionality for divergent transitions and treedepth:

<img width="799" alt="image" src="https://github.com/epinowcast/epidist/assets/29818116/df1a8e96-aee7-4283-86f0-314db978aee6">

**Comment by seabbs** [comment]
I think you should be able to pull what you need from the `cmdstan` object? https://github.com/epinowcast/epinowcast/blob/d957b21af07c7708d8ae28fc248fffe39d453828/R/model-tools.R#L277

**Comment by athowes** [comment]
I found a way to do it with `brms`.

**Comment by athowes** [comment]
I found that running using `brms` it saves to `stanfit` so you can't access the `cmdstanr` class functions.

I also have been finding it hard to do it with `brms` directly (I got the maximum treedepth but not the number of times it has been hit).
