### ISSUE TITLE
List Adam as package maintainer?

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#135]
I think it would make sense to list me as the package maintainer. Going forward I expect to be the person most involved with development of the package and the best point of contact about a question. Currently the package maintainer is Daniel.

What do you think @seabbs @parksw3 @kgostic?

**Comment by seabbs** [comment]
Let's have a chat about this next meeting? I think it essentially comes down to if you will be able to do long term maintenance on this. I hope the answer is yes but likely does need a f2f chat?

**Comment by athowes** [comment]
I'd be in favour of me doing long term maintenance.

**Comment by parksw3** [comment]
I also agree that this is a good idea.

**Comment by athowes** [comment]
On call we agreed this being appropriate for the time being, but to be reviewed in Autumn regarding the longer term future of package maintenance.
