### ISSUE TITLE
Remove `cmdstanr` remote dependency

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#147]
See #143. Eventually we should try to rely on a stable version of `cmdstanr`. This would be required for this package to be on CRAN. One way to achieve this is via additional repos argument in `DESCRIPTION`.

**Comment by seabbs** [comment]
>  One way to achieve this is via additional repos argument in DESCRIPTION

We can do this now without waiting for it to be on CRAN

**Comment by athowes** [comment]
So far I am just trying:

```
Additional_repositories:
    https://github.com/stan-dev/cmdstanr/releases
```

Looking through GitHub I didn't find instances of use of Additional_repositories with R universe which is what I had been trying to do before (https://stan-dev.r-universe.dev/cmdstanr).

See https://github.com/r-lib/remotes/issues/618.

**Comment by athowes** [comment]
The solution (I think) was to use same approach as `primarycensoreddist`.

Also I am trying to move `cmdstanr` from Imports to Suggests.

**Comment by athowes** [comment]
Need to change default away `backend = "cmdstanr"`
