### ISSUE TITLE
Which models to keep? 

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#15]
We currently have a range of models that have been ported over from the research code base. @parksw3 we need to decide which of these to keep prior to any work being done on these. 

I think my proposal would be keep just the latent truncation and censoring adjusted model and the dynamic backward -> forward models and with the view we will likely have a few more models flavours in the near future (as various improvements on those).

**Comment by athowes** [comment]
@seabbs @parksw3 @kgostic do you think we have a consensus about which models to keep based on Friday's meeting?

As I understand it, seems like we had mild agreement on deprecating any functions which were close to "pure" `brms` and writing up a vignette showing how to do that instead (see https://github.com/epinowcast/epidist/issues/9).

Perhaps I could start by making a PR to remove all of these, and in the meantime we can get clarity about which of the others to keep?

**Comment by seabbs** [comment]
I thought we had a roadmap which was to strip back to just the latent censoring and truncation model with feature issues to add support for retrospective (so no truncation), and the dynamic method (for edge cases/where only backwards distributions are available). 

If we want to keep any other models I think we should make adding them in as features and drop for now (so the current action can be to drop and add a issue review those models for later additions).

**Comment by parksw3** [comment]
Sorry, I've been getting emails for all the issues, and I'm just getting to them after work, so I missed that I was tagged in this one... I also agree with Katie that we're only keeping one.

**Comment by seabbs** [comment]
(if the emails are annoying you can turn off github emails in the settings and just use github notifications)

**Comment by parksw3** [comment]
Thanks, that would be nice... I had to go through ~70 emails just now, which adds a huge mental block for me (more so than the actual task of reviewing issues)...
