### ISSUE TITLE
Installation not (yet) possible through runiverse

### ISSUE THREAD

**Issue by jamesmbaazam** [epinowcast/epidist#156]
You currently suggest to install `epidist` through `install.packages(r universe link)` but the package is not in https://epinowcast.r-universe.dev/packages, so it fails.

**Comment by athowes** [comment]
Thanks James! Agree we should fix this, and rewrite the `README` (#61)

**Comment by jamesmbaazam** [comment]
> I think we might want to hold off on this slightly until we hit the goals of `0.1.0`

Yep, so maybe remove the current install instruction from the README?
