### ISSUE TITLE
Improve merge queue when many PRs are stacked

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#178]
I think there is an interaction between our GitHub actions concurrency settings and our merge queue. When multiple actions are queued it looks like it sometimes cancels things. 

Actions are: 

1. Investigate if this is actually happening. If it is for which actions.
2. Look at GitHub actions docs + google. Is this a common issue + any suggested solutions
3. If yes to 2. then apply fix
4. If no to 2. my guess is its fairly simple and so just need to look at the docs for concurrency?

**Comment by athowes** [comment]
Which CI action is being cancelled? Is it all? Is it one?

Could just turn merge queue off?
