### ISSUE TITLE
Gamma delay model convergence and parameter recovery 

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#180]
Within PR #171 I have been trying to get the gamma delay model to 1. converge and 2. recover simulated parameters. So far I've not done this. A successful PR to close this issue should do those two things, or understand why they might not be possible. There are two tests that should pass (which I'm pasting here with some scratch code included):

## Test 1: convergence

```
test_that("epidist.epidist_latent_individual fits and the MCMC converges  in the gamma delay case", { # nolint: line_length_linter.
  skip_on_cran()
  set.seed(1)
  
  gamma_family <- epidist_family(
    prep_obs_gamma,
    family = "gamma",
    dpars = c("mu", "shape"),
    links = c("log", "identity"),
    lb = c(0, 0),
    ub = c(NA, NA)
  )

  gamma_formula <- epidist_formula(prep_obs_gamma)
  gamma_formula$pforms$sigma <- NULL
  gamma_formula <- brms::bf(gamma_formula, as.formula("shape ~ 1"))
  
  gamma_prior <- brms::prior("normal(0, 3)", class = "Intercept") +
    brms::prior("gamma(0.01, 0.01)", class = "Intercept", dpar = "shape", lb = 0)
    
  fit_gamma <- epidist(
    data = prep_obs_gamma,
    family = gamma_family,
    prior = gamma_prior,
    formula = gamma_formula,
    seed = 1,
    brms::brm
  )
  
  expect_s3_class(fit_gamma, "brmsfit")
  expect_s3_class(fit_gamma, "epidist_fit")
  expect_convergence(fit_gamma)
})
```

## Test 2: recovery

```
test_that("epidist.epidist_latent_individual recovers the simulation settings for the delay distribution in the gamma delay case", { # nolint: line_length_linter.
  skip_on_cran()
  set.seed(1)
  
  gamma_family <- epidist_family(
    prep_obs_gamma,
    family = "gamma",
    dpars = c("mu", "shape"),
    links = c("log", "log"),
    lb = c(0, 0),
    ub = c(NA, NA)
  )
  
  gamma_formula <- epidist_formula(prep_obs_gamma)
  gamma_formula$pforms$sigma <- NULL
  gamma_formula <- brms::bf(gamma_formula, as.formula("shape ~ 1"))
  
  # Fix the shape intercept to log(2) so that it corresponds to simulated value
  gamma_prior <- brms::prior("normal(0, 3)", class = "Intercept") +
    brms::prior("constant(0.6931472)", class = "Intercept", dpar = "shape")
  
  fit_gamma <- epidist(
    data = prep_obs_gamma,
    family = gamma_family,
    prior = gamma_prior,
    formula = gamma_formula,
    seed = 1
  )
  
  # What the value is of the delay i.e. mu = 2/3
  mean(prep_obs_gamma$delay)
  
  draws_gamma <- posterior::as_draws_df(fit_gamma$fit)
  draws_gamma_mu <- exp(draws_gamma$Intercept)
  
  expect_equal(mean(draws_gamma_mu), mu, tolerance = 0.1)
})
```

## Strategies to use here

* Playing around with links to get it right
* Fitting a basic `brms` gamma model to the delays (no latent)

**Comment by parksw3** [comment]
This is really dumb of me but I'm getting stuck on 

```
fit_gamma <- epidist(
	data = prep_obs_gamma,
	family = stats::Gamma(link = "log"),
	formula = list(mu ~ 1, shape ~ 1)
)
```

due to the following error:

```
Error in formula.default(object, env = baseenv()) : invalid formula
```

**Comment by parksw3** [comment]
Just confirming that the gamma distribution on its own works fine using `brms`. So it's either censoring or truncation that's messing up. I feel like it might be the censoring that's messing up the gamma because it messes up the left tail... Here's the code I used to test the raw delays.

```
library(epidist)
library(brms)
set.seed(101)

obs_time <- 25
sample_size <- 500

shape <- 2
rate <- 3

# The mean of the gamma distribution is: shape / rate
mu <- shape / rate

sim_simple_gamma <- rgamma(1000, shape=shape, rate=rate)

data_simple_gamma <- data.frame(
	delay=sim_simple_gamma
)

gfit_simple <- brm(delay ~ 1, data=data_simple_gamma,
									 family=Gamma(link="log"))

draws_gamma_simple <- posterior::as_draws_df(gfit_simple)

mean(exp(draws_gamma_simple$Intercept)) ## 0.69 which gives small bias

sim_obs_gamma <- simulate_gillespie() |>
	simulate_secondary(
		dist = rgamma,
		shape = shape,
		rate = rate
	)

## looks good
plot(density(sim_obs_gamma$delay))
curve(dgamma(x, shape=shape, rate=rate), col=2, add=TRUE)
lines(density(sim_simple_gamma), col=3)

# this gives estimate of 0.67032, which isn't too far away from trugh
# and CIs still contain truth
gfit_all <- brm(delay ~ 1, data=sim_obs_gamma,
								family=Gamma(link="log"))

sim_obs_gamma_subset <-
	sim_obs_gamma[sample(seq_len(.N), sample_size, replace = FALSE)]

## looks good too, I guess
plot(density(sim_obs_gamma$delay))
curve(dgamma(x, shape=shape, rate=rate), col=2, add=TRUE)

# this gives estimate of 0.7046881 which is a bit high but
# CIs still contain the true value
gfit_subset <- brm(delay ~ 1, data=sim_obs_gamma_subset,
									 family=Gamma(link="log"))
```

**Comment by parksw3** [comment]
I wonder if this is also because the test case has a really low mean? Before I try fitting, I tried comparing the density of gamma samples (black) vs density of latent variables (`runif(1, min=x["stime_lwr"], max=x["stime_upr"])-runif(1, min=x["ptime_lwr"], max=x["ptime_upr"])`), latter looks pretty horrible:

![Rplot](https://github.com/user-attachments/assets/53a3b526-dbf7-48a9-8a97-18a6cf74d038)

Code:

```
library(epidist)
library(brms)
set.seed(101)

sample_size <- 500

shape <- 2
rate <- 3

# The mean of the gamma distribution is: shape / rate
mu <- shape / rate

sim_obs_gamma <- simulate_gillespie() |>
	simulate_secondary(
		dist = rgamma,
		shape = shape,
		rate = rate
	) |>
	observe_process()

gamma_unif_sample <- apply(sim_obs_gamma, 1, function(x) 
	runif(1, min=x["stime_lwr"], max=x["stime_upr"])-runif(1, min=x["ptime_lwr"], max=x["ptime_upr"]))

plot(density(sim_obs_gamma$delay))
lines(density(gamma_unif_sample), col="2")
```

**Comment by parksw3** [comment]
But if we assume a much bigger mean, things are looking fine.

![Rplot](https://github.com/user-attachments/assets/9b36d1ba-3fe8-43e2-9bee-22c7e52e8cb8)

Code:

```
library(epidist)
library(brms)
set.seed(101)

sample_size <- 500

shape <- 2
rate <- 2/10

# The mean of the gamma distribution is: shape / rate
mu <- shape / rate

sim_obs_gamma <- simulate_gillespie() |>
	simulate_secondary(
		dist = rgamma,
		shape = shape,
		rate = rate
	) |>
	observe_process()

gamma_unif_sample <- apply(sim_obs_gamma, 1, function(x) 
	runif(1, min=x[["stime_lwr"]], max=x[["stime_upr"]])-runif(1, min=x[["ptime_lwr"]], max=x[["ptime_upr"]]))

plot(density(sim_obs_gamma$delay))
lines(density(gamma_unif_sample), col="2")
```

**Comment by parksw3** [comment]
I still can't figure out why the gamma family is not working for me through epidist so I can't test convergence but I suspect that simulating data with low mean is the main issue with recovery... for example, we're assuming a mean of 6.8 for the lognormal case. If we test the lognormal case with a similarly low mean, we'll probably run into similar issues. I think we had similar issues when we were working on the first version/long paper...

**Comment by athowes** [comment]
> This is really dumb of me but...

Probably not! I think it's just that the last PR that went in updated the formula interface to use `brms::bf(mu ~ 1, shape ~ 1)` rather than a `list`. This just happened on Friday I think so hadn't been updated in this branch (have done that now).

**Comment by seabbs** [comment]
>  I think we had similar issues when we were working on the first version/long paper...

Yes we did. I agree this is likely an issuel

**Comment by athowes** [comment]
Moving to longer delay times fixes the convergence issue, but doesn't fix the recovery issue.

The recovery issue might be because Stan gamma parameterisation is: `gamma_lpdf(reals y | reals alpha, reals beta)`

When we create the `latent_gamma_lpdf` even though the vectors are called `mu` and `shape` I don't know that `gamma_lpdf` handles it properly:

```
real latent_gamma_lpdf(vector y, vector mu, vector shape, vector pwindow,
                           vector swindow, array[] real obs_t) {
  int n = num_elements(y);
  vector[n] d = y - pwindow + swindow;
  vector[n] obs_time = to_vector(obs_t) - pwindow;
  return gamma_lpdf(d | mu, shape) - gamma_lcdf(obs_time | mu, shape);
}
```

I'm pretty sure this is the issue:

```
> mean(exp(draws_gamma$b_shape_Intercept))
[1] 0.09029047
> mean(exp(draws_gamma$b_Intercept))
[1] 9.316328
```

Matching the simulation settings:

```
shape <- 10
rate <- 1 / 10
```

(Even though you'd sort of expect it to be that the intercept exponential recovers the mean, not the shape parameter [the first parameter of the Stan parameterisation]).

**Comment by parksw3** [comment]
Ohhh this is tricky... is there a way we can add parameter transformation depending on the family within `epidist_stancode.epidist_latent_individual` through some clever use of `paste0` or something? `brms` must be doing some kind of internal transformation too to get over this issue... but `brms` code is way too deep for me to find out where/how exactly this is done...

Specifically, we could consider doing something like

```

  stanvars_functions <- brms::stanvar(
    block = "functions",
    scode = epidist_stan_chunk("latent_individual/functions.stan")
  )

  family_name <- gsub("latent_", "", family$name)

if (family_name==Gamma) {
 gsub("int n = num_elements(y);", "vector alpha=shape; vector beta=shape/mu; int n = num_elements(y); ", stanvars_functions[[1]]$scode)
}

  stanvars_functions[[1]]$scode <- gsub(
    "family", family_name, stanvars_functions[[1]]$scode
  )
```

this is super hacky but it should works...?

**Comment by athowes** [comment]
Thanks @parksw3!

I've added an issue about this here https://github.com/epinowcast/epidist/issues/226!

I agree we could find a hacky solution that works for the gamma as it is but since we'd like all families to work with `epidist` then I think we'll have to get deep into the `brms` code and figure out how they do it. Planning to have a go.
