### ISSUE TITLE
Meta issue for FAQ suggestions

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#182]
In PR #181 we added an FAQ section to the website. As the package is used more we should look to answer a wider range of questions / provide more tips.

Here we can:

1. Collect any potential tips (please contribute if you have suggestions!)
2. Consider how we might systematically get FAQ questions from users

For 2. we might think about recording these in some kind of bug hunt / test demo / presentation / ... -- perhaps worth thinking about which venues we could present the package or get early testing from users?

**Comment by athowes** [comment]
Oops! Intended to put this here:

> Deal with Sam's comment about "Document an approach to deal with stochastically failing models." -- I'm unclear on exactly what this means. As in what to do if your model fails to fit? And how to document this would be a vignette? Or write in the epidist roxygen that you can call epidist_diagnostics and try to debug? Let me know.

Comment from https://github.com/epinowcast/epidist/issues/163#issuecomment-2232922382.

**Comment by athowes** [comment]
In #281 @athowes writes:

> Taken from appendix of https://github.com/epinowcast/epidist/pull/52: how does this rvars stuff work?

```r
obs_prep |>
  as.data.frame() |>
  add_predicted_rvars(fit) |>
  select(.prediction) |>
  head()
```

> Should we be recommending ahead of the draws versions?

**Comment by athowes** [comment]
Add documentation in FAQ covering how to do proper prediction (like the Ebola vignette):

> This was discussed F2F. From my POV my understanding is that:
> 
>   1. The Ebola vignette does demonstrate how to do this with a fitted model when you use `tidybayes` (and you can set `pwindow` and `swindow` and `relative_obs_time`)
> 
>   2. Hence I am unsure what more needs to be done here to close this. I recall some kind of suggestion of additional documentation?
> 
>   * Note that in future we might have functions to help users more here ([Functionality to support users with `modelr::data_grid` into `newdata` #280](https://github.com/epinowcast/epidist/issues/280))
> 
>   * I can see putting something about this into the FAQ sooner? Am I right that that's the suggestion here?
>       
>     * Perhaps include something about `primarycensoreddist`?

**Comment by seabbs** [comment]
Are the actionable steps taken here and so its ready to close?  If not I think we should pull them out and close this

**Comment by athowes** [comment]
I'd say they are of questionable actionability. Nonetheless I will pull out and close this and if we want to decide to close the individual issues we can.
