### ISSUE TITLE
Add functionality for generating individual or strata level delay distribution samples

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#188]
In #170 we added functionality to create `mean` and `sd` columns to `data.table`s which contain parameters from either the lognormal or gamma distributional parameters (with the possibility to implement any other required distributions).

Now we want to add functionality to allow users to easily generate the delay distributions they most care about. A first example of this would be the delay distribution estimate for each individual, or strata, in the model. This object should then naturally be able to be passed into `add_natural_scale_ mean_sd` (and indeed we will likely call it within the added function). I think plotting functionality can also be built around the output.

One question to answer here is whether this should be

1. Individual-level: i.e. as many outputs as there are data points
2. Strata-level: i.e. as many outputs as there are strata, e.g. 1 if intercept only, or say the number of areas if it's a spatial model

In the current unit test:

```
test_that("add_natural_scale_mean_sd.lognormal_samples works with posterior samples from the latent lognormal model", { # nolint: line_length_linter.
  skip_on_cran()
  set.seed(1)
  prep_obs <- as_latent_individual(sim_obs)
  fit <- epidist(data = prep_obs, seed = 1)
  ld_mu <- brms::posterior_linpred(fit, transform = TRUE, dpar = "mu")
  ld_sigma <- brms::posterior_linpred(fit, transform = TRUE, dpar = "sigma") 
```

if found a way to do the individual one. Perhaps we should provide both, but broadly I think the strata is preferred. Also, we should really be enabling people to predit whatever they want if we can. Need to think about how to do this / play with available `brms` functionality.

## Notes

```
# Below contains implementation notes:

# Need to modify this (i.e. "latent_lognormal")
fit$family

# (Which includes these names for the link functions needed)
fit$family$link
fit$family$link_sigma

# To work with these existing brms prediction functions
brms::posterior_epred(fit)
brms::posterior_predict(fit)

pp <- brms::prepare_predictions(fit)
pp$dpars$mu$fe$b
pp$dpars$sigma$fe$b

fit$family$family <- "lognormal"
fit$family$name <- "lognormal"

str(fit$family)
brms::posterior_predict(fit)
```

* Is `brms::prepare_predictions(fit)` used inside `posterior_linpred`?
* Check whether order of classes matter

**Comment by seabbs** [comment]
yes I agree we should use the newdata approach. We can also provide some functionality to either help users extract unique data points from there data (the simple version of all strata) and potentially to grid expand this to all combinations (i.e observed/unobserved) but I think the first pass should just be creating a nice interface to the predictive abilities of brms that works with new data and with our custom probability family distributions.

**Comment by athowes** [comment]
Possibility of adding a `summary` function here?

**Comment by seabbs** [comment]
yes agree
