### ISSUE TITLE
Class constructor for `family_samples`

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#191]
> Could have class constructor for this.

_Originally posted by @athowes in https://github.com/epinowcast/epidist/pull/170#discussion_r1691512681_

I'm a little bit unsure exactly how this would slot into the package, but we could have class constructors / validators for the `family_samples` classes.

Of course it would be good to check that something is a valid `family_samples`.

It wouldn't fix the awkwardness of e.g.

```
secondary_dist <- data.table(mu = 1, sigma = 1)
secondary_dist <- as_lognormal_samples(secondary_dist)
add_mean_sd(secondary_dist)
```

seeming a bit much (lots of code).

**Comment by athowes** [comment]
I think it won't be the only function, though perhaps other functions will operate on the output of e.g. `add_mean_sd` say.

And I agree users won't use it much.

**Comment by athowes** [comment]
Labelling this as wontfix as I don't know that we need it.

**Comment by seabbs** [comment]
I think we no longer need this so closing.
