### ISSUE TITLE
Review pre and postprocessing functions

### ISSUE THREAD

**Issue by kgostic** [epinowcast/epidist#20]
After removing all but one models in #15, we should also review the other functions in the package and decide what to keep.

@seabbs maybe we should discuss this at another meeting?

**Comment by athowes** [comment]
(I'll be working through this a bit while writing vignette[s], documenting functions, adding tests etc.)

**Comment by athowes** [comment]
Closing this as to be discussed within https://github.com/epinowcast/epidist/discussions/133.
