### ISSUE TITLE
Redo prior predictive check to have no extreme outliers

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#212]
> It would be better but the plot is hard to make because of the outliers

_Originally posted by @athowes in https://github.com/epinowcast/epidist/pull/203#discussion_r1697310330_

The priors we've set currently are still not good enough that there aren't draws which are obviously not plausible. Hence we should update with new priors until we are able to plot. The fact that the plot isn't viable is a red flag that the priors aren't good enough.

**Comment by seabbs** [comment]
Yes agree makes sense. If you get the chance can you chuck the current plots in here

**Comment by athowes** [comment]
I've started working on this over at https://github.com/epinowcast/epidist/pull/253.

I've updated the priors to be:

```r
prior_new <- brms::prior("normal(2, 0.25)", class = "Intercept") +
    brms::prior("normal(0, 0.25)", class = "Intercept", dpar = "sigma")
```

This produces histograms / densities on the mean and standard deviation like:

![image](https://github.com/user-attachments/assets/347bd154-1002-46eb-b6d3-708ccc85c7fe)

With summaries:

```
> summary(pred$mean)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  3.236   5.612   6.979   7.974   9.201 165.109 
> summary(pred$sd)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
   0.3667    1.7170    2.7066    5.2036    4.4656 3039.5363 
```

If I were to take issue with these priors it would be:

* Minimum mean at 3.236 is too high
* Maximum mean at 165.109 could be too low -- what about e.g. HIV (long delay)
* Maximum SD at ~3000 seems too high. That's something like 8 years

What are your opinions on this @seabbs @kgostic @parksw3? Would be happy to get your opinion about these prior, then I'll have another go at finding something suitable.

**Comment by athowes** [comment]
Additionally, I found a bug in the formula for lognormal SD which I have corrected on this PR (https://github.com/epinowcast/epidist/pull/253/commits/d17c8cf0a17047c782fd966b132234c1c09cece6).

**Comment by athowes** [comment]
Here's my more finalised proposal for the updated priors:

```r
             prior     class coef group resp  dpar nlpar lb ub source
      normal(1, 1) Intercept                                   family
 normal(-0.7, 0.4) Intercept                 sigma             family
```

![image](https://github.com/user-attachments/assets/b791701a-4282-4512-9c83-4393085bc19d)


```r
> quantile(pred$mean, c(0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99))
        1%        10%        25%        50%        75%        90%        99% 
 0.3261811  0.8870048  1.6399314  3.3526381  6.5098351 11.9413446 35.1323644 
> quantile(pred$sd, c(0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99))
        1%        10%        25%        50%        75%        90%        99% 
 0.1298726  0.4092331  0.8195731  1.7660744  3.9831374  8.3403952 31.0626779 
```
