### ISSUE TITLE
Create `delay_summary` function built on `predict_delay_parameters`

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#215]
Can use something like:

```
  summarised_draws <- draws[,
    list(
      mean = mean(value, na.rm = TRUE),
      median = median(value, na.rm = TRUE),
      q2.5 = quantile(value, 0.025, na.rm = TRUE),
      q5 = quantile(value, 0.05, na.rm = TRUE),
      q20 = quantile(value, 0.2, na.rm = TRUE),
      q35 = quantile(value, 0.35, na.rm = TRUE),
      q65 = quantile(value, 0.65, na.rm = TRUE),
      q80 = quantile(value, 0.8, na.rm = TRUE),
      q95 = quantile(value, 0.95, na.rm = TRUE),
      q97.5 = quantile(value, 0.975, na.rm = TRUE)
    ),
    by = by_cols
  ]
```

Main questions here for me are handling of how we name the groups for the samples. I think this will have interplay with #213 and the possible output of that function.

For example do we just want numbers like 1, ... or do we want to have different columns like age, location, sex, ... and then the corresponding samples (and eventually summaries). Should mention that in issue #213.

**Comment by seabbs** [comment]
We could also just write a summary.delay_samples method

**Comment by athowes** [comment]
See here for maybe useful resource on this: https://github.com/epiforecasts/scoringutils/pull/876/files

**Comment by seabbs** [comment]
I don't think that is useful?

I think our main choice is : 

1. `summary` method
2. `aggregate` method
3. our own custom s3.

**Comment by athowes** [comment]
I thought that you had sent the `scoringutils` [link above](https://github.com/epiforecasts/scoringutils/pull/876/files) with the suggestion that it'd be useful for this issue. Did you mean it'd be useful for another issue? If so, which?

**Comment by athowes** [comment]
I'm moving this to not planned for the time being as I expect this can be handled by `tidybayes` after some initial investigation.
