### ISSUE TITLE
Properly discretised PMF functionality

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#218]
> Should we have functionality for getting a "properly" discretised PMF in this package or somewhere else?

_Originally posted by @athowes in https://github.com/epinowcast/epidist/issues/210#issuecomment-2262694949_      

In PR #210 we added functionality to predict the delay distribution parameters (internal and natural scale).

A reasonable thing to want to do with these parameter samples is to get some features about the implied discretised delay distribution (e.g. a PMF).

One thing you could do to generate a sample from the delay:

1. Draw from delay parameters (empirically from the draws we have available)
2. Draw from delay distribution

This would get you a continuous delay draw.

Then what you could do is naively discretised that draw to get a PMF. @seabbs says that this is bad and I am a bad person for having suggested it. So, we should either implement the correct thing here, or rely on some other package to do it (or we create that package).

This [function](https://package.epinowcast.org/reference/simulate_double_censored_pmf.html) in `epinowcast` might do what we want (but badly for some reason?).

**Comment by athowes** [comment]
See comment https://github.com/epinowcast/epidist/pull/210#issuecomment-2263357277 from Sam

**Comment by seabbs** [comment]
> (but badly for some reason?)

It approximates via lots of random draws (i.e its just crude). Not bad ... just misguided

**Comment by athowes** [comment]
This was discussed F2F. From my POV my understanding is that:

1. The Ebola vignette does demonstrate how to do this with a fitted model when you use `tidybayes` (and you can set `pwindow` and `swindow` and `relative_obs_time`
2. Hence I am unsure what more needs to be done here to close this. I recall some kind of suggestion of additional documentation?
  * Note that in future we might have functions to help users more here (https://github.com/epinowcast/epidist/issues/280)
  * I can see putting something about this into the FAQ sooner? Am I right that that's the suggestion here?
  
Tagging @seabbs.

**Comment by seabbs** [comment]
> I can see putting something about this into the FAQ sooner? Am I right that that's the suggestion here?
Perhaps include something about primarycensoreddist?

Yes exactly

**Comment by athowes** [comment]
Would you be OK with me moving this into the "add FAQ" issue and closing this one?

**Comment by seabbs** [comment]
I would prefer to avoid meta-issues but you can if you want. I thinks its fine to do a PR that does them all at once

**Comment by athowes** [comment]
I see what you mean but find it mentally confusing to have this here. I can have the meta issue then create nicer scoped sub issues.
