### ISSUE TITLE
weird pushes?

### ISSUE THREAD

**Issue by parksw3** [epinowcast/epidist#225]
**Describe the bug**
I was trying to fetch the most recent repo but GitHub Desktop was telling me I needed to push first (even though I didn't commit anything). Now, GitHub is showing a message saying "[approximate-inference-vignette](https://github.com/epinowcast/epidist/tree/approximate-inference-vignette) had recent pushes 1 minute ago" but I also don't see any new commits that happened through my ghost push... just making an issue to make sure nothing goes wrong and in case someone is wondering why GitHub is flashing that there's a new push...

**Comment by athowes** [comment]
Odd -- don't see anything strange on my end I think!

**Comment by seabbs** [comment]
hmm very odd

**Comment by parksw3** [comment]
ok github is not showing the message any more and none of you see this as a problem so I'm resolving it...
