### ISSUE TITLE
Stan and `brms` parameterisation issue

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#226]
In `brms` every family has a `mu` parameter. For example, the gamma distribution parameterisation is `mu` (the mean) and `shape` (the shape parameter).

As such, the fitted `brms` output for a gamma distribution has `Intercept` and `Intercept_shape` parameters.

However, in our `latent_individual` model we create the following likelihood:

```
real latent_gamma_lpdf(vector y, vector mu, vector shape, vector pwindow,
                           vector swindow, array[] real obs_t) {
  int n = num_elements(y);
  vector[n] d = y - pwindow + swindow;
  vector[n] obs_time = to_vector(obs_t) - pwindow;
  return gamma_lpdf(d | mu, shape) - gamma_lcdf(obs_time | mu, shape);
}
```

This likelihood passes `mu` and `shape` to `gamma_lpdf` in Stan. The parameterisation which [`gamma_lpdf`](https://mc-stan.org/docs/2_18/functions-reference/gamma-distribution.html) accepts is `alpha` (shape) and `beta` (inverse rate).

In PR #184 we found that the gamma `latent_individual` model can recover simulation parameters when you take into account that `Intercept` (which you would naively think would be for the mean) is actually for the shape parameter (because that is the first parameter that goes into `gamma_lpdf`.

So we need a solution to this more broadly, not just for the gamma ideally.

`brms` must be doing something internally to handle these transformations, so I think the first step is to understand what it is doing.

**Comment by athowes** [comment]
There might be some ideas in here:

* https://github.com/paul-buerkner/brms/blob/ddd34fceee58e1927b3d6885910e009e96c45d83/R/stan-predictor.R#L2151

A possible workaround is that we rewrite the Stan `_lpdf` functions to use the `brms` parameterisation. Can just do this by making a light wrapper. Hopefully the Stan code would use the version implemented in the file rather than the Stan version? I don't know. This does involve writing wrappers outselves but I think it's going to be the easiest thing / it's pretty quick to do for the realistic range of families anyone would input.

**Comment by athowes** [comment]
I think given these difficulties, we might want to try harder to rely on inbuilt methods for `brms` creating the Stan code here such as the `T[]` and `cens` stuff.

**Comment by seabbs** [comment]
> I think given these difficulties, we might want to try harder to rely on inbuilt methods for brms creating the Stan code here such as the T[] and cens stuff.

I still expected this to be very hard
