### ISSUE TITLE
Vector or real meta bug

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#235]
We have two issues where the problem of creating a custom Stan function but not knowing if the inputs are `vector` (which is what we have currently) or `real` causes bugs:

* [ ] https://github.com/epinowcast/epidist/issues/227 (bug 2)
* [ ] https://github.com/epinowcast/epidist/issues/222

These are settings where you don't have a model for a particular distributional parameter, and then it's a `real` not a `vector`.

To solve these two issues, we need to check if there is a model on each distributional parameter, and if there isn't then put it to `real` in the custom Stan code rather than `vector`. There also needs to be code to turn that `real` into a `vector` and dispatch on the `latent_lognormal_lpdf` (etc.).

The comments of https://github.com/epinowcast/epidist/issues/222 has more discussion between @seabbs and I on a way to do this. I'm not 100% sure of the route yet, but I think it's doable.

As it's somewhat unlikely a user would not specify a model on a quantity, I'd call this "nice to have" for version 0.1.0 rather than strictly required.

**Comment by kgostic** [comment]
I think @seabbs will be more helpful with this than me, but my high-level thought is that maybe there's a way to set up the custom stan code so that there's one convention that we use all the time (e.g. can we always use a vector, which is sometimes length 1)?

**Comment by seabbs** [comment]
> Or some way to accept multiple types as arguments in Stan / C++.

Yes function overloading
