### ISSUE TITLE
Postprocessing meta

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#238]
Tagging @seabbs @kgostic @parksw3 for feedback:

## Background 

The existing issues we have about postprocessing are as follows:

* [x] #213
* [x] #214
* [x] #215

We have already implemented some postprocessing functionality, including including

* The `add_mean_sd` function https://github.com/epinowcast/epidist/pull/170
* The `predict_delay_parameters` function https://github.com/epinowcast/epidist/pull/210
* (Not merged) the `all_strata_newdata` function which would feed into `predict_data_parameters` https://github.com/epinowcast/epidist/pull/231/files

By extension of the `all_strata_newdata` function I can see a path to achieving the postprocessing functionality that we intially agreed for 0.1.0 of the package. However, it'd be better if we don't have to write this functionality outselves. Therefore:

## Plan

My plan going forward is to follow Plan A until it seems like there are roadblocks that make it not possible or too difficult for some reason. At that point I'll follow Plan B.

## Plan A

* Use #48 to do DDD exploration of the possibility to use `tidybayes` (or other packages) for all post-processing
* Figure out the extent to which #214 is required
  * Split #214 into the easier and harder part #240
* I think this workflow will also cover "summary" type functions, so no need for #215

### Plan B

*  Return to https://github.com/epinowcast/epidist/pull/231 in order to implement the functionality that we need for 0.1.0
* To be determined: after how much effort on Plan A should I decide it's not possible?
  * I have quite a strong expectation that Plan A is possible
  * Postprocessing in some ways blocks figure creation

**Comment by seabbs** [comment]
Agree with the proposed roadmap

**Comment by athowes** [comment]
I have done some initial light investigation into `tidybayes` and it has updated me further todays Plan A being possible and desirable.

**Comment by seabbs** [comment]
There is also https://marginaleffects.com/

**Comment by seabbs** [comment]
Can we safely delete [sensible-newdata-input](https://github.com/epinowcast/epidist/tree/sensible-newdata-input) or does it contain work we need?

**Comment by athowes** [comment]
> Can we safely delete [sensible-newdata-input](https://github.com/epinowcast/epidist/tree/sensible-newdata-input) or does it contain work we need?

We can delete it. I will do so.

**Comment by athowes** [comment]
I think that with the Ebola vignette up we have now demonstrated how to do the postprocessing tasks that we had scope / previously talked about, and this can be closed as completed.
