### ISSUE TITLE
Expected delay variance using `tidybayes`

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#241]
The `tidybayes` package via `brms` has functionality to get the expected prediction `.epred`.

What we might also like to do is to get the expected prediction variance. This is implemented in `add_mean_sd` but perhaps there is a more native way to do it.

**Comment by athowes** [comment]
From @seabbs:

* This is not in `tidybayes`
* Write a helper function yourself and do it from samples. See e.g. this [question](https://discourse.mc-stan.org/t/how-can-i-find-the-posterior-sd-with-a-non-normal-distribution/27286)
* One option which is very generic (good) but wasteful (bad) is to:
  1. `.epred` distributional parameters
  2. Sample from the continuous distribution parameters some number of times
  3. Summarise samples by mean, median, SD etc.
  4. Use these

**Comment by seabbs** [comment]
I think in terms of a standard interface then the last (wasteful) workflow seems like a good thing to support as it will work for all families regardless of what has or hasn't been implemented. Once that is there we can circle back and think about 2/or pushing for it to get better ecosystem support.

**Comment by athowes** [comment]
Should we unexport `add_mean_sd`?

**Comment by seabbs** [comment]
yes

**Comment by seabbs** [comment]
I think we should make a new issue for the work (enhancing add_mean_sd and renaming predict_delay_parameters) vs tracking both here and in #428. Do you agree these are near duplicate @athowes?

**Comment by athowes** [comment]
Yes they're near duplicate and can be rewritten into one issue.

**Comment by athowes** [comment]
Closed in favour of https://github.com/epinowcast/epidist/issues/471.
