### ISSUE TITLE
Consider setting intercept on any distributional parameters without a model

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#266]
In PR #255 we moved to allowing `bf(mu ~ 1)` to be the default for the `formula` option of `epidist()`.

This means that users now do not need to specify a model on the distributional parameters of the model (aside from `mu`) if they don't want to.

Although this is nice, it does now mean that:

1. We must be specifying priors on both the `Intercept_dpar` and `dpar` parameters in `epidist_family_prior()`
2. If we have any post-processing which relies on knowing model names (e.g. `Intercept_dpar`) then it'll be more fiddly

An alternative proposal is to set `dpar ~ 1` for any `dpar` left without a model. This would fix the two problems above but introduce its own problems:

1. Users may be confused that we've changed their model in the output
2. If a user puts a prior on `dpar` as an override then it won't easily work with the new `Intercept_dpar` parameter. Further: perhaps it's good to allow users to be putting priors on the distributional parameter itself, rather than the intercept

For the time being I'm happy to stick with things as they are, but if the downsides become more painful for some reason I could be convinced to switch approaches.

**Comment by seabbs** [comment]
I think this is a nice summary and I think the only way we can decide this is to confront some users with the current design and ask them.
