### ISSUE TITLE
Use labels and milestones to organise development issues

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#27]
As per the title it would be good to overall our issues list to use labels based on the type of work and organise these into milestones (ideally with an associated kanban board) for planning purposes. This should then lead to some docs or an issue template so that all new issues are also organised in this way.

**Comment by athowes** [comment]
I have added an "infrastructure" tag with the same hex as in `epinowcast`.

**Comment by athowes** [comment]
Perhaps we can talk about this next meeting @seabbs @kgostic @seabbs. That is generating milestones and possibly setting up a kanban board.

**Comment by athowes** [comment]
I think I'm blocked on making this kanban board by epinowcast community permissions.

I can create a "project" on my own account:

<img width="256" alt="image" src="https://github.com/epinowcast/epidist/assets/29818116/75b42124-a9f4-483c-9b40-26c9589dd41e">

But for that, I can only add issues from repos that I am the owner of.

If I go to "Projects" direct from `epinowcast/epidist` then I have:

<img width="957" alt="image" src="https://github.com/epinowcast/epidist/assets/29818116/09c96141-c9fa-4248-b59f-fcf879b658e3">

And I can't create a new project.

Let me know if you have a good way to fix this / any workarounds @seabbs.

**Comment by athowes** [comment]
I do now have this working. But I am not currently using it.

Perhaps next meeting we can move towards the workflow being more that we agree on issues for that week and organise them in the kanban board. Or we use the silly dinosaur names.

Perhaps part of me thinks this is overkill and it's going OK organising the work to do more informally. Might be different if the development was occuring across more different people.

**Comment by seabbs** [comment]
I don't like the sprint names or approach and am okay with it being fairly ad-hoc for now. I think post this week/next though we might want to start thinking about release numbers and hence milestones etc as we look to make Dev more formal. I'm flexible as to when we do that though (i.e could keep going for a month or more as is)

**Comment by athowes** [comment]
Closing this as covered by #233.
