### ISSUE TITLE
Depend on `primarycensoreddist` in custom family `brms` functions

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#275]
The [initial version](https://github.com/epinowcast/primarycensoreddist/releases/tag/v0.1.0) of `primarycensoreddist` was just made available. It is an R package which has the functions:

* [dprimarycensoreddist()](https://primarycensoreddist.epinowcast.org/reference/dprimarycensoreddist.html) [dpcens()](https://primarycensoreddist.epinowcast.org/reference/dprimarycensoreddist.html): Compute the primary event censored PMF for delays
* [pprimarycensoreddist()](https://primarycensoreddist.epinowcast.org/reference/pprimarycensoreddist.html) [ppcens()](https://primarycensoreddist.epinowcast.org/reference/pprimarycensoreddist.html): Compute the primary event censored CDF for delays
* [rprimarycensoreddist()](https://primarycensoreddist.epinowcast.org/reference/rprimarycensoreddist.html) [rpcens()](https://primarycensoreddist.epinowcast.org/reference/rprimarycensoreddist.html): Generate random samples from a primary event censored distribution

We should be able to use these functions to replace our implementations in `posterior_predict_family` and `log_lik_family` (I don't think for `posterior_epred_family`). This would reduce code duplication (we are just replacing the distribution basically in some of these functions, while copy pasting code currently).

**Comment by athowes** [comment]
> Agree. FYI the aim is to release `primarycensoreddist` to CRAN by the end of next week.

Updates on timeline for this? From `README` looks like it's not on CRAN at the moment?

**Comment by seabbs** [comment]
its not submitting tomorrow/weds

**Comment by seabbs** [comment]
you could just depend on this via a universe and update when it hits cran but so more gated by effort to do the code changing I think

**Comment by athowes** [comment]
I don't think this is urgent so from my POV happy to wait until it's on CRAN.

Unless the timeline for acceptance after submission to CRAN is weeks +?

**Comment by athowes** [comment]
Flag that `primarycensored` is on CRAN now I think, so this can go in

**Comment by athowes** [comment]
This is closed by #442.
