### ISSUE TITLE
Find a way for Ebola vignette with HMC to be faster

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#289]
HMC is a bit slow for the Ebola vignette models:

```r
> rstan::get_elapsed_time(fit$fit)
        warmup sample
chain:1 18.386  8.755
chain:2 17.760  8.716
chain:3 17.357  8.797
chain:4 19.231  8.667
```

```r
> rstan::get_elapsed_time(fit_sex$fit)
        warmup sample
chain:1 19.995  9.445
chain:2 20.034  9.464
chain:3 18.804  9.461
chain:4 19.785 11.334
```

```r
> rstan::get_elapsed_time(fit_sex_district$fit)
        warmup sample
chain:1 23.020 10.194
chain:2 23.363 10.280
chain:3 23.112 10.212
chain:4 23.523 10.255
```

However, it's better that we use HMC (see comments of @seabbs and @kgostic on PR #48 e.g. https://github.com/epinowcast/epidist/pull/52#discussion_r1742081309). Perhaps we need some kind of caching method here not to rerun the longer models?

**Comment by athowes** [comment]
However.. all those issues about model fit were fixed by using HMC. So failure here for Laplace:

![image](https://github.com/user-attachments/assets/24850f32-975f-46be-b8f5-d47f03ba046a)


Just going to bite bullet on it being a bit slow to run and maybe we can fix it to use some kind of cache approach at some point.

**Comment by athowes** [comment]
Use e.g. https://www.kloppenborg.ca/2021/06/long-running-vignettes/ here?

**Comment by seabbs** [comment]
Closing in favour of #30
