### ISSUE TITLE
Refactor of `observe_process`

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#291]
`observe_process` creates columns `ptime_daily` and `stime_daily`. This seems to be strange to me. What if the columns are already daily (e.g. https://github.com/epinowcast/epidist/pull/52#discussion_r1742271807)? What if we want something other than daily level of censoring? This suggests function refactoring to me.

**Comment by seabbs** [comment]
The current approach is 100% hardcoded for the original paper we need to think carefully about the preprocessing i.e should this function even exist.

**Comment by athowes** [comment]
Dupe of #33
