### ISSUE TITLE
Prefer doing `package::function` in the text and not the code? 

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#295]
In f2f you said you preferred just doing `package::function` in the text and not the code but here I see it everywhere. Note that using `brms::ranef()` will auto link in `pkgdown` but I think the current approach will not?

_Originally posted by @seabbs in https://github.com/epinowcast/epidist/pull/52#discussion_r1750572702_

**Comment by athowes** [comment]
Added to https://github.com/epinowcast/epidist/issues/290

**Comment by seabbs** [comment]
IMO I would prefer specific issues which can be handled in clean PRs var large meta-issue
