### ISSUE TITLE
Package notes

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#296]
I see 

'::' or ':::' imports not declared from:
  'lubridate' 'scales'

in #292

**Comment by athowes** [comment]
I think this will be closed by https://github.com/epinowcast/epidist/pull/309

**Comment by athowes** [comment]
Don't think I see these issues in https://github.com/epinowcast/epidist/actions/runs/10812621802/job/29994676700 anymore (we call `library` on those packages now)
