### ISSUE TITLE
Implement delay-based censoring

### ISSUE THREAD

**Issue by parksw3** [epinowcast/epidist#30]
This is a longer-term goal but we should implement delay-based censoring models as discussed last week for computational efficiency.

One problem is that the shape of the prior distribution for the delay-based censoring would depend on different combination of censoring widths and prior distributions. In the simplest case, let's say we have a 4 day censoring window for the delay. This could be done by either (1) 2 day intervals for both primary and secondary events or (2) 1 day interval for primary events and 3 day interval for secondary events. These two scenarios would require different priors for the delay-based censoring. 

I feel there's some more research to be done in this area but I also think this would be a practically important issue.

**Comment by seabbs** [comment]
I think that the marginal model (i.e `primarycensored`) might have got us what we need here so closing. Please reopen if you think there is more to do here.
