### ISSUE TITLE
Try using marginal effects for post-processing

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#302]
> There is also https://marginaleffects.com/

_Originally posted by @seabbs in https://github.com/epinowcast/epidist/issues/238#issuecomment-2305087347_

I think if we could use `marginaleffects` somewhere in one of the vignettes it might be nice to demonstrate its use as an alternative to `tidybayes`. Perhaps it has some new functionality as well, I'm not sure.

**Comment by seabbs** [comment]
Agree.  I think I would save for another or a specific vignette and I agree the priority is fairly low

**Comment by athowes** [comment]
Suggest to put this into FAQ.
