### ISSUE TITLE
No model meta

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#307]
In the case that there is no model on a parameter we can either

1. Work around it by setting appropriate priors (#305)
2. Enforce there being a model by putting `~ 1` internally (https://github.com/epinowcast/epidist/issues/266)

This is a meta issue for deciding between these options, or suggesting new ways to handle this.

**Comment by seabbs** [comment]
I strongly think we should do 2 for simplicity

**Comment by kgostic** [comment]
Agreed in meeting that we're doing 2.

**Comment by athowes** [comment]
* Also shift to `brms` style formula input.
* If given string then add on all other formula as constant
* Require formula on everything if given `brms::bf()`
* Have to also deal with the fixing stuff to a constant case

**Comment by seabbs** [comment]
sounds good

**Comment by athowes** [comment]
> `bmr(mu ~ 1 +w wefwef)`

What's this?

**Comment by seabbs** [comment]
yes exactly sorry should have been clearer

**Comment by athowes** [comment]
Closing as outdated / no longer relevant.
