### ISSUE TITLE
Preprocessing meta

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#313]
# Preprocessing strategy

* Add modular functions to preprocess data. Mostly involving creating new columns
  * I like the `add_*_vars` format for names
* It's possible in future some of these could be S3.
* Then do issue to put these functions into `as_latent_individual` and simplify
* These functions will also have them available for other class constructors and for users running simulation studies etc.

## Observation times

Add observation time column and create relative observation time column https://github.com/epinowcast/epidist/issues/384
* Possible names: `add_obs_time`, `add_obs_vars`, `add_obs_time_vars`, `add_time_vars`

## Censoring columns

Add censoring columns. User provides lower and window, or lower and upper https://github.com/epinowcast/epidist/issues/33
* Possible names: `add_censor_vars`, `add_event_vars`

**Note: there will be another function about going from exact event time to lower and upper: see simulation section**

## Delay columns

The function to create `delay_lwr` and `delay_upr` could be its own function
* Possible names: `add_delay_bounds`, `add_delay_vars`

## Conversion functions

Something to help users go from dates to integers. Perhaps this could be a part of the observation times function.

# Note on simulation functionality

We are making the choice here to split out simulation functionality. This would include:

1. Functions to truncate date like #34
2. Functions which add upper and lower given exact observation times: takes `ptime` and `stime` and does the `_floor_mult`

These functions should be constructed in the same spirit as the preprocessing ones but be separate. Perhaps some prefix. To be worked on after preprocessing

**Comment by kgostic** [comment]
After meeting, rough suggestion

- Remove `observe_process()`
- Edit add latent individual to follow https://primarycensoreddist.epinowcast.org/dev/reference/pcd_as_cmdstan_data.html
- Update preprocessing step in Ebola vignette

This is a rough proposal. We'd like Adam to expand on this issue and get some feedback before we jump.
