### ISSUE TITLE
Panel C too small in Ebola vignette

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#319]
<img width="691" alt="image" src="https://github.com/user-attachments/assets/0abf5a81-4f58-4787-a823-86d302139728">

This is too small.

Options:

* Try making bigger. Unsure if it's easy, I did try but hard to get feedback loop on it
* What about y-axis labels here, maybe cut down
* What about gridlines? Seem like too many. Remove minor ones?

**Comment by seabbs** [comment]
make the fig longer using the Rmd options?
