### ISSUE TITLE
Refactor `observe_process` function

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#33]
## New plan

* Create `add_event_vars` function to add upper and lower given either lower and window or lower and upper
* Enforce our names structure which is `ptime_lwr` and `ptime_upr` (i.e. change the names)
* Find a way to slot the back into existing functionality so as not to break anything for now

## Old

I've just used `observe_process()`. Some notes on possible refactor:

* The name "observe process" is vague and seems misleading for what it is doing. For my understanding, what it is doing is implementing interval censoring. If so, the name should reflect that.
* If it is implementing interval censoring, then I think that there should be arguments available for specifying the censoring intervals. At the moment it looks like it's just using daily intervals, and some kind of fixed upper and lower.

**Comment by seabbs** [comment]
I think its implementing the observation process which in this instance is censoring but agree it can be renamed.

**Comment by athowes** [comment]
Even in this instance I'd think of the observation process as having multiple stages, including but not limited to censoring. I think having functions to modularly implement each part of the observation process would be nice.

**Comment by seabbs** [comment]
Yes agree

**Comment by athowes** [comment]
As a part of this issue, I propose to:

* [ ] rename `observe_process()` to something to represent interval censoring,
* [ ] include arguements for the intervals to be used,
* [ ] create unit tests for the function,
* [ ] fill out the `roxygen2` documentation for the function.

**Comment by athowes** [comment]
> As a part of this issue, I propose to:
> 
>     * [ ]  rename `observe_process()` to something to represent interval censoring,
> 
>     * [ ]  include arguements for the intervals to be used,
> 
>     * [ ]  create unit tests for the function,
> 
>     * [ ]  fill out the `roxygen2` documentation for the function.

I am now working in this direction.

**Comment by athowes** [comment]
Note on implementation:

* I think we should be using `.floor_mult` here to round down to the nearest multiple of `x`
* I guess there is a question about whether people are censoring their data or they are taking already censored data and adding some columns. Maybe it just works the same either way...
* I think we should be letting users input `x`
* Probably we can let there be different censoring windows used for primary and secondary
  * Then I think we can re-use the names `pwindow` and `swindow` for the sizes of these
* I don't know why we have `_daily` as new columns. If I just delete these does it do anything? Use code search to find all instances of `_daily`

**Comment by athowes** [comment]
I've drafted a function that would look like this:

```r
observe_process <- function(linelist, pwindow = 1, swindow = 1) {
  assert_numeric(pwindow, lower = 0)
  assert_numeric(swindow, lower = 0)
  
  linelist |>
    mutate(
      ptime_lwr = .floor_mult(.data$ptime, f = pwindow),
      ptime_upr = .data$ptime_lwr + pwindow,
      stime_lwr = .floor_mult(.data$stime, f = pwindow),
      stime_upr = .data$stime_lwr + swindow,
      delay_lwr = pmax(0, .data$stime_lwr - .data$ptime_lwr - 1),
      delay_upr = .data$delay_lwr + pwindow + swindow
    )
}
```

If users provide data where `stime` and `ptime` are already censored to the lower bound then this would do nothing and add the upper bounds.

I'm also interested as to why in the original code the upper bound for the delay was the lower bound plus one. Isn't this wrong? The upper bound should be plus two?

**Comment by athowes** [comment]
Expaning upon

> f users provide data where stime and ptime are already censored to the lower bound then this would do nothing and add the upper bounds.

then I think we can do two things with this function:

1. Add the `upr` columns needed for input into future model functionality to data that already is censored to the lower
2. Add the `lwr` and `upr` columns to data that has no censoring

**Comment by athowes** [comment]
Tag @seabbs for comment on above before I begin working on PR #352 again (don't want to go off in wrong direction).
