### ISSUE TITLE
Refactor `epidist_family` to use double dispatch

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#338]
In PR https://github.com/epinowcast/epidist/pull/335 we refactored `epidist_family` to absorb the `brms` reparameterisation code required.

<details><summary>Details</summary>
<p>

```r
epidist_family.epidist_latent_individual <- function(data,
                                                     family = "lognormal",
                                                     ...) {
  epidist_validate(data)
  # allows use of stats::family and strings
  family <- brms:::validate_family(family)
  non_mu_links <- family[[paste0("link_", setdiff(family$dpars, "mu"))]]
  non_mu_bounds <- lapply(
    family$dpars[-1], brms:::dpar_bounds, family = family$family
  )
  custom_family <- brms::custom_family(
    paste0("latent_", family$family),
    dpars = family$dpars,
    links = c(family$link, non_mu_links),
    lb = c(NA, as.numeric(lapply(non_mu_bounds, "[[", "lb"))),
    ub = c(NA, as.numeric(lapply(non_mu_bounds, "[[", "ub"))),
    type = family$type,
    vars = c("pwindow", "swindow", "vreal1"),
    loop = FALSE
  )
  reparam <- family$dpars
  if (family$family == "gamma") {
    reparam <- c("shape", "shape ./ mu")
  }
  custom_family$reparam <- reparam
  return(custom_family)
}
```

</p>
</details> 

What we should probably do now is refactor `epidist_family` to double dispatch on `data` and on `family` so that the "family-specific" parts (like the reparameterisation) can be shared across models. Something like:

```r
epidist_family <- function(data, family) {
  epidist_family_model(...)
  epidist_family_family(...)
}
```

This might be a bit odd to make nice but we can try. It also is hard because `family = "lognormal"` is not in a family class so how can we dispatch on it?

**Comment by athowes** [comment]
>  It also is hard because family = "lognormal" is not in a family class so how can we dispatch on it?

Opinions on this problem @seabbs? Starting to work on this now.

**Comment by seabbs** [comment]
We do the same as brms and at input turn it into one
