### ISSUE TITLE
Badge showing failing tests even though main is fine?

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#347]
To fill.

**Comment by athowes** [comment]
<img width="473" alt="image" src="https://github.com/user-attachments/assets/371682d9-a07d-4bd2-8eed-c7f21e5d15ac">

This shows as passing now. So I'm guessing transient and closing.

**Comment by seabbs** [comment]
i.e. here: https://github.com/epinowcast/epidist/actions/workflows/R-CMD-check.yaml
