### ISSUE TITLE
Improve hex sticker

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#353]
Make this better:

![image](https://github.com/user-attachments/assets/5c0ef3da-93ab-4e48-99b0-dcb602605c86)

**Comment by seabbs** [comment]
I was fairly happy with it with the previous colour scheme to be honest

**Comment by seabbs** [comment]
In terms of res just store a higher res original and then use use_this for the generation of the stuff that will be used everywhere else

**Comment by athowes** [comment]
Opinions on:

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/ebdf77e2-7250-464c-8c57-70d1e4168ab3">

**Comment by athowes** [comment]
`usethis::use_logo` doesn't seem to do anything apart from put it in `man/figures/logo.png` so unsure it has a purpose.

**Comment by seabbs** [comment]
it generates a bunch of favicons for pkgdown and resizes it appropriately I believe.

**Comment by athowes** [comment]
> it generates a bunch of favicons for pkgdown and resizes it appropriately I believe.

It doesn't generate files other than `man/figures/logo.png` for me.

**Comment by seabbs** [comment]
https://pkgdown.r-lib.org/reference/build_favicons.html

**Comment by seabbs** [comment]
I like the colour scheme reversion. I don't love the zoom on the partial distribution but I don't ultimately mind that much so happy to go forward with it if its your preference

**Comment by seabbs** [comment]
See: https://github.com/epinowcast/epidist

We may need usethis:use_logo or similar approaches to dealing with whitespace after all.

**Comment by seabbs** [comment]
(look in dark mod)

**Comment by seabbs** [comment]
Closed in favour of #363
