### ISSUE TITLE
Make logo transparent outside hex for dark mode

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#363]
(look in dark mode)

_Originally posted by @seabbs in https://github.com/epinowcast/epidist/issues/353#issuecomment-2388331975_

**Comment by athowes** [comment]
FWIW I don't think a logo having whitespace on darkmode is "high priority"

**Comment by seabbs** [comment]
IMO this is high as it represents a reduction in package quality of what we had previously/a bug

**Comment by seabbs** [comment]
This wasn't an issue previously right so reverting is something to consider if we want a quick fix (and could just revert the plot size change). I struggle to see how this can't be a very fixed issue elsewhere in package land though.

**Comment by athowes** [comment]
Solution is here https://stackoverflow.com/questions/60426922/trim-around-hexagon-shape-with-hexsticker

**Comment by athowes** [comment]
I think easy fix will do soon

**Comment by athowes** [comment]
> Solution is here https://stackoverflow.com/questions/60426922/trim-around-hexagon-shape-with-hexsticker

You might want to consider this over at `EpiNow2` as looks to me like there will be same issue
