### ISSUE TITLE
Standardise `linelist` and `data` names

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#381]
In some places in the code we use `linelist` for a dataframe and in other places we use `data`.

I think that we should standardise this. I'd probably be in favour of using `data` everywhere.

One could push back saying that they are different things e.g. `linelist` is before processing and `data` is after processing. I don't think this matters too much and a name like `linelist` is never going to be able to describe all the types of data we want to import so we shouldn't bother with the enterprise.

**Comment by athowes** [comment]
I wonder if we need a generic name for "data class".

I don't think we should use `linelist` as input to things unless they only work with `epidist_linelist`.

**Comment by seabbs** [comment]
Yes agree lets use data
