### ISSUE TITLE
Create data for use in tests

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#40]
> I like the idea of moving data simulation into its own vignette. Also want to point out that it's considered a best practice to include a separate data generation script in the /data subdirectory for reproducibility: https://r-pkgs.org/data.html

_Originally posted by @kgostic in https://github.com/epinowcast/epidist/issues/9#issuecomment-2110474065_

I think that we should have some test data generated with a script in `data-raw` that is saved to the package. Perhaps it should only be accessible internally. I'm reading https://r-pkgs.org/data.html to figure out how to best do this. Then many tests can just import that data without generating it.

**Comment by athowes** [comment]
> for some thoughts on how to do this

As in have it in `data/`? And it be accessible?

**Comment by seabbs** [comment]
No - see the PR but CRAN often pushes back against this https://stackoverflow.com/questions/13463103/inst-and-extdata-folders-in-r-packaging

I don't have a strong opinion on this but CRAN often does.
