### ISSUE TITLE
Rename `latent_individual` and `direct_model` for consistency

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#400]
Adam to fill...

**Comment by seabbs** [comment]
At the same time as addressing this we might want to address the naming structure for custom distributions: https://github.com/epinowcast/epidist/blob/03609f990ed112492969a21b3e99ccd19de2d90e/R/latent_lognormal.R#L59

**Comment by athowes** [comment]
> At the same time as addressing this we might want to address the naming structure for custom distributions: 

Yes more broadly this is the naming for custom families. Which would include the name in `epidist_family` and then the name in `log_lik`, `epred` and `pred` methods.

**Comment by athowes** [comment]
What about just:

* `direct_model`
* `individual_model`
* `cohort_model`

i.e. do we need the `latent_` part in `latent_individual`?

**Comment by athowes** [comment]
* `latent_model`
* `marginal_model`

**Comment by athowes** [comment]
@kgostic notes this needs to be documented clearly.

**Comment by athowes** [comment]
* `naive_model`
* `latent_model`
* `marginal_model`

@athowes to implement name change.

**Comment by athowes** [comment]
https://www.pymc.io/projects/docs/en/stable/api/gp/generated/pymc.gp.Marginal.html

**Comment by seabbs** [comment]
ha nice okay good point. Also pymc is looking cool these days

**Comment by athowes** [comment]
Closed by #441.
