### ISSUE TITLE
Update description while we have chance

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#401]
Right now we have: "Estimate epidemiological delay distributions for infectious diseases"

On the RHS we have: An R package for estimating epidemiological delay distributions 

I'd say "epidemiological delay distributions for infectious diseases" is pretty good / central though it does narrow us more than we actually are (it's not just epidemiological). Also, do we need to say "for infectious diseases"? What about non infectious diseases? Nothing about the methods is infectious specific?

Should we say with `brms`? I think we should. Maybe "Stan" has more name recognition?

Should we say it's an R package? Perhaps we don't need to say this.

**Comment by athowes** [comment]
1. What is the domain of the package
2. Should we change the title

@kgostic mentions that the package could also be used for titre data.
 * Tools for survival analysis in some sense

@athowes
  * Notes that we can create vignettes demonstrating other application areas
  
In F2F:
  * Drop the word infectious diseases
  * Include `brms`
  * CRAN doesn't accept "R package" so we can't do that
  
Two proposed options:

1. Estimate epidemiological delay distributions with `brms`
2. Extending `brms` for estimating epidemiological delay distributions

Could also use "models for..." or "tools for...".

**Comment by seabbs** [comment]
I think my current merging of peoples views is 

Estimate epidemiological delay distributions by extending brms

 I don't want people to think that this is just using brms as it makes the sell of why use this vs brms directly harder

**Comment by athowes** [comment]
GH comments doesn't have vote capacity so @seabbs @kgostic @parksw3 please provide ranked choice / thoughts / preferences on the following names:

A. Estimate epidemiological delay distributions with `brms`
B. Extending `brms` for estimating epidemiological delay distributions
C. Estimate epidemiological delay distributions by extending `brms`

**Comment by athowes** [comment]
For me I'm not convinced it's required to say "extending" (see e.g. another `brms` extension [package](https://discourse.mc-stan.org/t/flocker-an-r-package-for-occupancy-modeling-with-brms/34132)). Seems trivial it's an extension else why would we have written a whole package.

So for that reason my preference is with A.

If we want to use "extending" then B reads more naturally than C. So I'm pretty indifferent between B and C.

**Comment by seabbs** [comment]
you can do it with tapback responses

**Comment by parksw3** [comment]
I agree B reads better than C. And A reads better than B. So I like A.

**Comment by seabbs** [comment]
Okay lets go with A then as that seems like the group decision? I would prefer not stan as I have had direct feedback that its a negative but I don't feel that strongly

**Comment by parksw3** [comment]
sounds good

**Comment by jamesmbaazam** [comment]
I missed out on this conversation but I would have suggested something like "Estimate epidemiological delay distributions using Bayesian Multilevel Models" instead of `brms` because the current suggestions focus on the engine, which could be swapped out.

**Comment by athowes** [comment]
That's fair.

We thought that "Bayesian" could be intimidating.

I think given where the package is now it's quite tightly woven into using `brms` and I'm not sure that it could be swapped out.
