### ISSUE TITLE
Clean up solvable check notes

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#404]
I see: 

* checking R code for possible problems ... [11s] NOTE
.make_intercepts_explicit: no visible global function definition for
  'as.formula'
  (D:/a/epidist/epidist/check/epidist.Rcheck/00_pkg_src/epidist/R/utils.R:122)
Undefined global functions or variables:
  as.formula
Consider adding
  importFrom("stats", "as.formula")

I also see notes about the use of internal brms functions. Have we opened issues with `brms` to see if those can be exported?

**Comment by athowes** [comment]
Yes I can fix the `.make_intercepts_explicit` one.

We have at least one issue open on `brms`.

**Comment by seabbs** [comment]
> importFrom("stats", "as.formula")

This one should also be very easy
