### ISSUE TITLE
Create news item

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#425]
We (I) have been neglecting having news updates. What we could do is retrospectively create a `news.md` based on all of the PRs which have been merged. I think this would likely not be terribly informative though.

We could also just create something summarising what is in the package for initial release.

**Comment by pearsonca** [comment]
I think NEWS.md is generally a good idea. I'd argue in this case you can have a single bullet which corresponds to the initial release, and then actual news items accumulating with changes post initial release.

Probably also remind yourself to do these going forward by adding it to the PR template (along w/ version bumps).
