### ISSUE TITLE
CFA contribution update

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#429]
* Copyright
* Something in README
* ...

Example: how Posit deals with this. Say https://dplyr.tidyverse.org/

**Comment by seabbs** [comment]
Identifying as a funder is probably what we want

**Comment by athowes** [comment]
I think possibly the Posit one uses custom template https://tidytemplate.tidyverse.org/

**Comment by kgostic** [comment]
I think Sam should put Insight NET as a funder if that's the capacity in which he worked on this. I'm not sure if contractor time needs to be explicitly acknowledged...
