### ISSUE TITLE
Make posterior_predict_latent etc. use function factories

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epidist#442]
rather than requiring a function per distribution as we do now. At the same time we should update to use `primarycensored` vs the current custom functionality.

**Comment by athowes** [comment]
We agreed on an initial package release on 2024-11-21 (tomorrow). This is a somewhat large feature which doesn't appear to have work on it currently. I would suggest it might be future work rather than included in the release.

**Comment by seabbs** [comment]
See `issue442`. I see this as on the critical release path as its a large feature change (going from limited to all probability distributions) and required for new models (which can share some elements (like posterior prediction)

**Comment by seabbs** [comment]
I doon't mind making a small release to tick things off but I I think this needs doing before bringing in users
