### ISSUE TITLE
Use `checkmate` for argument checking

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#45]
Have lots of functions which use something like a `data.table` with certain column names. Need to make sure the inputs to these functions are valid. Currently not doing this. See: https://mllg.github.io/checkmate/

**Comment by seabbs** [comment]
We also have a specific data.table checker in Epinowcast that @pearsonca is spinning out  into coerce_dt. Not sure we need that here though.

**Comment by athowes** [comment]
Going to close this issue as I have now used `checkmate` in closed PRs and would be confident about using it in future work.
