### ISSUE TITLE
Reorder function sections on website

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#451]
They should be presented in a natural order.

**Comment by athowes** [comment]
I'd suggest a natural order would be:

* Simulation
* Linelist data
* Model fitting
* Direct model
* Latent model
* (Marginal model)
* Postprocess
* Diagnostics
* Family
* Formula
* Prior
* Stan code
* Simulation
* Data

I wonder if it's possible to put some text in here also which groups the sections. Like something saying "you probably won't need to edit or use these unless you want to engage with making new models" for the family, formula, prior, and Stan code.

**Comment by seabbs** [comment]
Simulation is in twice but I like it towards the end otherwise this seems like a good structure. I think that all functions for a given model should be together and we probably want a s3 generic section that describes the methods one needs for a model to a dataset.

**Comment by athowes** [comment]
Just do reordering and then make another issue.
