### ISSUE TITLE
Create function use flowchart

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#46]
Use `mermaid` to show suggested path through use of functions in package:

```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

See example in https://github.com/CDCgov/Rt-without-renewal/tree/main/EpiAware#current-epiaware-model-diagram.

**Comment by seabbs** [comment]
Note that what this won't do is build the flow diagram of how user facing functions should be used together (i.e it just does what calls what) which means it is a slightly different (but still useful) thing.

**Comment by athowes** [comment]
Here's the static analysis:

![image](https://github.com/epinowcast/epidist/assets/29818116/a0be86ac-9b39-4c8b-a4c3-8c0848c01803)

**Comment by seabbs** [comment]
My TLDR from this is that most of the package is user facing with users expected to glue functions together (which is no bad thing IMO) and that most of the internal code is in data setup/preprocessing
