### ISSUE TITLE
Add `priorsense` to FAQ

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#466]
In #371 @seabbs writes:

> Add `priorsense` and `loo_epred` to the FAQ as useful user facing tool options
> 
> https://bsky.app/profile/avehtari.bsky.social/post/3l5ls7qjcpq26
> 
> https://bsky.app/profile/avehtari.bsky.social/post/3l5haushmjh2a

_Originally posted by @athowes in https://github.com/epinowcast/epidist/issues/182#issuecomment-2393641122_

**Comment by seabbs** [comment]
This is already in
