### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by parksw3** [epinowcast/epidist#5]
**Is your feature request related to a problem? Please describe.**
PR request seem to be failing due to a lack of unit tests.

**Describe the solution you'd like**
Add unit tests.

**Describe alternatives you've considered**
No alternatives.

Maybe we can brainstorm a few unit tests that would be useful and I'd be happy to add them...

**Comment by seabbs** [comment]
So there are a few things here. Usually we would want a unit test to test thee "unit" level behaviour i.e each function does what we expect. We would then also want integration tests (do some collection of functions do what we expect) and then end to end tests (which would be can be fit a model from raw data for example). 

To get the test coverage passing we need: 

- [ ] `testthat` structure (i.e a folder for `test`) this can be setup using `usethis`. 

For the first test passes I agee it makes sense to do a simple fit and check the result (which would be an end to end). We probably want to decide which model fitting functions we are keeping in before we do that though?

**Comment by athowes** [comment]
Well scoped PR to add `testthat` structure with ~ a single test for end to end modelling with the primary function we pick? Can start writing this before resolution of #15 as it can just be swapped in easily enough. I think we are there with #15 anyway after Friday's meeting, but waiting for someone's confirmation on this.

**Comment by seabbs** [comment]
I think I would literally make a PR that just had a dummy test in it for starters. End to end testing can be tricky and will make coverage very hard to understand (as everything will look covered) so perhaps wee should focus on unit testing core parts of the code base first?

**Comment by seabbs** [comment]
(or exclude the end to end test from coverage stats)

**Comment by seabbs** [comment]
> g, but waiting for someone's confirmation on this.

@athowes can you clarify what you want confirmation on here?

**Comment by athowes** [comment]
I was refering to getting confirmation on which models to keep (https://github.com/epinowcast/epidist/issues/15). In that I didn't want to write a model test for a function we would deprecate.

But yes, the end to end testing does look more complicated to me than tests for each individual function. I'd be happy to start there instead.

I think I can look at some of the unit tests in e.g. `epinowcast` and start doing similar for the functions we have in `epidist`. Only worry is that I might do tests for something we end up getting rid of. I have some sense of what seems core to start with though.

**Comment by seabbs** [comment]
> I was refering to getting confirmation on which models to keep (https://github.com/epinowcast/epidist/issues/15). In that I didn't want to write a model test for a function we would deprecate.

Got you. 

> I think I can look at some of the unit tests in e.g. epinowcast and start doing similar for the functions we have in epidist. Only worry is that I might do tests for something we end up getting rid of. I have some sense of what seems core to start with though.

Agree. I think the order should be 

- [ ] Testing infra
- [ ] Cull functions
- [ ] Test what is left
- [ ] Features and robustness improvements

Looking at `epinowcast` might be a good shout or well done packages like `dplyr`

**Comment by athowes** [comment]
Closing this. Will create new issues for testing what is left and for feature and robustness improvements.
