### ISSUE TITLE
Improve documentation for simulate_gillespie() to better explain parameterisation

### ISSUE THREAD

**Issue by TimTaylor** [epinowcast/epidist#53]
Given that we have parameters `r` and `gamma` defined as
```R
#' @param r The rate of infection. Defaults to 0.2.
#' @param gamma The rate of recovery. Defaults to 1/7.
```
is the use of `beta` in the following lines muddled/erroneous?
https://github.com/epinowcast/epidist/blob/03cac6f7dc83b05ca6860965edbcd62175b6d449/R/simulate.R#L88-L93

If so I believe this would also effect the paper code at https://github.com/parksw3/epidist-paper/blob/main/R/simulate.R (but probably tangential to the results discussed).

Apologies for the noise if I'm mistaken.

**Comment by athowes** [comment]
I think this also looks suspicious. Perhaps one for @parksw3 or @seabbs?

**Comment by parksw3** [comment]
sorry, I think it's a problem with the documentation. In the SIR model, we have

$$
\begin{aligned}
dS/dt = -\beta S I/N\\
dI/dt = \beta SI/N - \gamma I
\end{aligned}
$$
where $r = \beta - \gamma$ represents the rate of initial epidemic growth rate. Does this clear things up?

**Comment by seabbs** [comment]
Thanks @TimTaylor and @parksw3 for the clarification. I think the action we should take here is update the docs for clarity?
