### ISSUE TITLE
Update figures in vignettes

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#55]
The figures in the vignettes are currently generated from scratch and do not follow the same theme as the figure functions in the package and associated paper(s).

We should definitely standardise the style.

We should decide on whether to use "from scratch" plots in our vignettes or package plots.

Further, we should review which plots there are the in package and which we want to keep. In some sense this is part of a broader issue, so perhaps that's out of scope for this issue.

**Comment by seabbs** [comment]
> We should decide on whether to use "from scratch" plots in our vignettes or package plots.

I think the question for at least the getting started vignette is if we have a package plot that does the same function and are not using it should we keep the function.

**Comment by athowes** [comment]
I agree. As part of this issue we should:

* [ ] Replace uses of handwritten plotting functions in the get started vignette with packaged versions OR delete packaged version
* [ ] Make any alterations to packaged versions

**Comment by seabbs** [comment]
I think we should have a clear inventory of what plotting the package currently has (maybe here) and discuss

**Comment by athowes** [comment]
We do not currently intend to include plots in this package so I think we can close this issue.
