### ISSUE TITLE
Solution for handling global variable warnings

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#63]
> how to handle global variable warnings package wide. I have a small preference for using the global variables functionality vs defining to NULLS

_Originally posted by @seabbs in https://github.com/epinowcast/epidist/pull/58#pullrequestreview-2082269661_

**Comment by athowes** [comment]
> The easiest way to deal with this is to pre-define those variables within your package and set them to NULL, optionally adding a comment (as is done in the refined version of gen below). When possible, you could also use a character vector instead of symbols (as in aggr below)

https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html

**Comment by sbfnk** [comment]
You could use https://github.com/anthonynorth/roxyglobals which introduces the `@autoglobals` to do the work for you.

**Comment by seabbs** [comment]
Ooo this is great

**Comment by athowes** [comment]
Closed via #101.
