### ISSUE TITLE
Facilitate user passing in priors

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#71]
## Goal

As a part of a Bayesian analysis, users of this package should be able to easily pass in prior distributions they would like to use. We should also provide sensible default options.

## Context

`epidist` interfaces via `brms` making it easy to help users pass in some priors. For other parameters (custom) then it's harder.

## Required features

- Update `epidist_priors` to document the names of the parameters that users can pass in
- Update `epidist::epidist` to accept input of priors
- Possibly change the default `brms` priors if we think there is good reason to   

## Out of scope

- Likely out of scope to allow for passing in priors for custom parameters (not the `brms` default ones)

## Related documents

- https://github.com/epinowcast/epidist/pull/70

**Comment by athowes** [comment]
I've been thinking about this and one thing we could do is like:

```
epidist_priors <- function(data, family, formula, ...) {
  default_prior <- brms::default_prior(
    object = formula,
    data = data,
    family = family
  )
  
  # Now replace parts of the default priors with user provided priors
  priors <- ...
  # Now warn user that "default brms prior used for parameter: ... pass in something to replace it..."
  return(priors)
}

```

What do you think @seabbs? Am playing with this at the moment.

**Comment by seabbs** [comment]
yeah could do it as the output and update the list using ModifyList

**Comment by athowes** [comment]
What do you mean by "as the output"?

The output of `epidist_priors` at the moment is being passed into `epidist`.

I'd imagine that the output is the list of priors, as required by `brms`.

I think that this should be the output, and then there should be a message about which default priors have been used.

Perhaps there could just be one message at the end to say how to change the priors.

Perhaps the messages could be set to be off by default somehow when passed in as default argument to `epidist` (don't want to spam user with too many messages, just want them to get this information if they care about changing the priors).

**Comment by seabbs** [comment]
epidist(..., priors = `ModifyList(epidist_priors(), sigma = blah blah blah)`)` 

could be a pattern
