### ISSUE TITLE
Agree on model name?

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#72]
## Goal

We should choose a shorter name for the "latent truncated censoring adjusted delay" model. This name would also be used as a class `modelname_epidist`.

## Context

* Originally called `latent_truncated_censoring_adjusted_delay`
* I have abbreviated to `ltcad` in #70 
* In thinking about this, we should consider whether the package will contain any models which are not "truncatation adjusted" or "censoring adjusted" i.e. how much does this need saying?

## Required features

- A shorter name
- It could be descriptive, it could not
- It should be compatible with our future model development interests (i.e. distinguishable from future models we might want to include)

**Comment by seabbs** [comment]
I think I vote that we assume (i.e unless we communicate otherwise) that all methods will account for right truncation and censoring at least and so this doesn't need to be explicitly stated. 

I think that due to this calling this latent would make sense. 

We could also call it after the paper it comes from (here ward) but that might get messy with multiple methods per paper (e.g. park)

**Comment by athowes** [comment]
Agree that focus should be on methods should account for right truncation and censoring.

Wonder if any methods that don't may be eventually included as teaching example. If so, could potentially use some naming to distinguish that they _don't_ account for (as in, accounting is default).

Calling "latent" doesn't really seem like a name to me. Latent variable model? Hierarchical model? Latent state model?

I think calling it after the paper isn't a very extensible strategy. Especially if we are expecting to be developing methods (which won't then have names).

**Comment by athowes** [comment]
@kgostic on call:

* Latent one acts act the individual level
* Down the road perhaps a delay one (group level)
* Think about which models we will have in future

@seabbs:

* Won't know which models we will have in the future
* `individual_latent_variable` seems reasonable

In theory could extract individual times for primary and secondary events.

People seem happy to be moving forward with this.

**Comment by seabbs** [comment]
Update from call that most people like `latent_individual` (or vice versa).
