### ISSUE TITLE
Use `as.class` type functionality to replace `epidist_prepare`

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#73]
## Goal

We may want to consider `as.class`, `is.class`, `validate.class`, functionality either in addition to our `epidist_prepare` methods or somehow replacing. The options are:

1. Replace
2. Addition
3. Don't add

I do not have a very clear picture about whether I prefer 1. or 2. or 3. at the moment and would need to think about it more.

## Additional

As a part of this PR I think we should fix the "no warnings on default" due to abuse of the `.default` #82.

## Related documents

- https://github.com/epinowcast/epidist/pull/70

**Comment by seabbs** [comment]
I think we want 1. probably

1. lets us have something that converts from a common data format but also interesting enables converting from one model data format to another which could be useful. 

If we did keep both its unclear to me what prepare would also do.

**Comment by athowes** [comment]
@seabbs on call:

* This adds the ability to convert between different data formats
* "i.e as_latent.delay_model would be a s3 method to map from a "delay_model" to the latent model"
* Do what is standard unless there is a reason not to
* Call `validate` when you put it into new functions at the start and also at the end of the conversion

**Comment by seabbs** [comment]
Here is some info on potential problems with a manual `validate_` function: https://github.com/epiforecasts/scoringutils/issues/816

**Comment by seabbs** [comment]
> Do what is standard unless there is a reason not to

If I had a bigger forehead I might get this tattooed

**Comment by athowes** [comment]
> If I had a bigger forehead I might get this tattooed

Male pattern baldness could make this feature more attainable within our current roadmap

**Comment by seabbs** [comment]
Judging by my family we are in luck

**Comment by athowes** [comment]
@seabbs here are my preliminary designs for the new functions:

```
as_latent_individual <- function(...) {
  UseMethod("as_latent_individual")
}
 
as_latent_individual.default <- function(data) {
  NULL
  # Takes data as input
  # Outputs an object of class latent_individual
  # The default one would take in data
  # Other ones could take in other model data formats
  # Advanced R suggests a constructor and a helper but I think we might just
  # want this single as function
}

validate_latent_individual <- function() {
  # Checks that the object of class latent_individual has the correct properties
  # Should be put in the top of any function that uses such objects
  # Also put it at the end of as_latent_individual methods
}
```

Let me know what you think.
