### ISSUE TITLE
Document `epidist_latent_individual` class specific functions

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#74]
The `epidist_latent_individual` class functions are currently not well documented.

I do not have a perfect picture of how to handle documenting instances of methods. (Also what the name is for functions like this e.g. `epidist_prepare.epidist_latent_individual`.)

As a part of 1. finding out best practise here 2. implementing then I'd also want the `roxygen2` website to display nicely (e.g. grouping together class specific functions?).

See #70.

**Comment by seabbs** [comment]
you can have a look at scoringutils here for one approach and there is a issue arguing about this (will look for)

**Comment by athowes** [comment]
I think the issue arguing about this might be https://github.com/epiforecasts/scoringutils/issues/793

**Comment by athowes** [comment]
Closing as outdated / non-actionable.
