### ISSUE TITLE
Consistent policy on namespace

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#81]
> we need to do something about our namespace. Are we: 

1. Not using the namespace nad only using `package::function` 
2. Using @importFrom in the roxygen
3. Both all the time
4. 2. and then sometimes 1. for uncommon functions

_Originally posted by @seabbs in https://github.com/epinowcast/epidist/pull/70#discussion_r1628984944_

Based on call with @seabbs, I currently prefer importing all functions from currently used packages (`data.table`, `ggplot2`, maybe `brms`) and then using `::` for other things. Perhaps this is only because I've never used the `roxygen2` version. Also if a user copy pastes the function out of their R console it won't have the `roxygen2` right?

**Comment by seabbs** [comment]
I think it would be unusual to use a mix of namespace and ::. If using the namespace at all I think we want everything in it but we can also use :: as you say

**Comment by athowes** [comment]
>  think it would be unusual to use a mix of namespace and ::. If using the namespace at all I think we want everything in it but we can also use :: as you say

Note that this is different to where we ended up I think.

This should be closed by #329.

**Comment by athowes** [comment]
Closed by https://github.com/epinowcast/epidist/pull/329.
