### ISSUE TITLE
Move `inst/s3-testing.R` somewhere

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#84]
Probably shouldn't have random testing files in `inst/`. Could:

1. Delete
2. Move to a test
3. Move somewhere else

**Comment by seabbs** [comment]
Move to test I think

**Comment by athowes** [comment]
Agree on moving to test. Will need to define what test is appropriate. I've just been using it as "Stan runs fine" so I imagine there are easy tests to add on that.

Have also added other small test snippets in there which should be moved to formal tests.

**Comment by athowes** [comment]
Closed via #106.
