### ISSUE TITLE
Expand getting started vignette

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#9]
The `epidist` [vignette](https://github.com/epinowcast/epidist/blob/main/vignettes/epidist.Rmd) is quite compact and possibly difficult to read for users not familiar with the package and methods already. I suggest expanding the writing to make it easier for new users to follow. The scope of this work would be to add further descriptions, links and references, figures, tables to the getting started vignette.

**Comment by athowes** [comment]
Suggest focusing this "Get started" vignette on clearly explaining use of the one (or perhaps two) primary modelling functions we select.

Suggests a natural additional vignette with comparison to approaches we don't think are very good (currently implemented in function code, but once deprecated can be implemented in raw `brms` as demonstration of how to do this).

**Comment by seabbs** [comment]
agree sounds like a good idea.

**Comment by athowes** [comment]
Rewriting this first "Get started" vignette with just the `latent_truncation_censoring_adjusted_delay()` model feels like a good way for me to zero in on what the important parts of the package are, and what value we are offering to users. I think it would also fit in with https://github.com/epinowcast/epidist/issues/16 (which feels a little abstract still, but I think one concrete part is to focus on writing vignettes and documentation).

Based on these considerations, this is what I'm going to start working on now.

**Comment by athowes** [comment]
In my view the "Getting started" vignette should be minimal and focus on:

* What is the problem that this package is solving (interval censoring and right truncation)
* How can I use the package as soon as possible with my data
  * What format do I need to put my data in so that is is compatible with the model function
  * How do I run the model function
  * How to do I extract / plot / otherwise work with the results of the model function
* For this reason, arguably "simulating data to use" should be deemphasised (this is not core functionality of the package
  * But having the data be simulated is helpful so that we can show that it works
  * Question here on how much to try to convince people that it works, versus leaving that to other vignettes
    * Something like showing how bad other approaches are is definitely something to put in other vignettes

**Comment by kgostic** [comment]
I like the idea of moving data simulation into its own vignette. Also want to point out that it's considered a best practice to include a separate data generation script in the /data subdirectory for reproducibility: https://r-pkgs.org/data.html

**Comment by athowes** [comment]
Posterior predictive check in the getting started vignette or another one? Look at simulate double censored PMF function in `epinowcast`.

**Comment by seabbs** [comment]
The reason. to simulate the censoring process in the vignette is to try and give people some visibility about what the observation process that is happening is with the hope they can maybe understand it. Now we have more papers trying to do this it seems like less of a priority but IMO is still a good idea as long as it doesn't take up too much space vs the rest of the getting started.

**Comment by athowes** [comment]
Yes agree it's a good idea to have the simulation in. A user hopefully should read the vignette and know better "what is censoring" and "what is truncation" than when they started. I think we can go a good way towards achieving that.
