### ISSUE TITLE
Add error on no method for class in cases where we use default

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#92]
For the `epidist_prepare` and `epidist` generics we use the default method to do something. For example to transform the data to the right class. Or to run the model without having the same generic for every model class. Here we need a different pattern to implement an error when you provide something of the wrong class. See #91.

**Comment by athowes** [comment]
With PR #125 then the `epidist_prepare` function will be removed.

So the only case where we have this pattern is in `epidist`.

I think there should be a good way to handle this in a one off pattern. Something like a warning unless the class of the object is from a specific list. Yes this means upkeeping this list but I don't think it's that bad. i.e.

```
stopifnot(inherits(..., c("possible1", "possible2"))
```

**Comment by seabbs** [comment]
I think we can instead dispatch on something where the default method is a warning?

**Comment by athowes** [comment]
Don't we then lose the default `epidist` working for all the models?

So we'd need:

1. Default method giving warning
2. Model 1 method
3. Model 2 method
4. Model 3 method
5. ...

Of course this is also fine but involves maintaining a method for each model right? Perhaps we might need that in the end when the models are different anyway.

**Comment by seabbs** [comment]
Its more complicated but it avoids hard coding a list into a function (which is bad as it prevents extension by a user). I think #151 would resolve this?

**Comment by athowes** [comment]
Yep #151 would solve it I think, good point. The `validate` function has a default that says no model
